# Site settings
title: I love Jazzyfact!
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Seongjun
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://seongjoon97.github.io # the base hostname & protocol for your site
